### ISSUE TITLE
Should you rename laravel5-snippets-vscode to laravel6-snippets-vscode?

### ISSUE THREAD

**Issue by anburocky3** [onecentlin/laravel5-snippets-vscode#21]
Since, **`Laravel`** releases latest version 6.0, why don't you update the package name to Laravel6.O?

**Comment by brysonreece** [comment]
Bumping; we're now in the 7.x release cycle.

**Comment by anburocky3** [comment]
That's great. i'm waiting for it.

**Comment by onecentlin** [comment]
Since 7.x just release, I will rename it later. =)

**Comment by onecentlin** [comment]
Only rename the description for VSCode extension
