### ISSUE TITLE
Laravel 9 new attribute syntax broken

### ISSUE THREAD

**Issue by tomorrowagency-brad** [onecentlin/laravel5-snippets-vscode#35]
Hi, I have the most recent version of this package installed, and Laravel 9 style Attributes are throwing an error. I'm not sure if this would be handled by this package or not. Please let me know if this is outside of the scope of your project, thanks!

![image](https://user-images.githubusercontent.com/98408295/154351615-6e5c003c-7a06-422a-854e-78c64c7c3cfa.png)

**Comment by tomorrowagency-brad** [comment]
False alarm, it was a problem with the php version I had linked by homebrew.

**Comment by onecentlin** [comment]
You may force php version in VSCode `settings.json`

Default is your php version in system

Change `php.validate.executablePath` value to your specified PHP version for validating.

```
"php.validate.executablePath": "/user/local/bin/php",
```

p.s. PHP 8.0 support named parameters
