### ISSUE TITLE
Incompatible with emmet - visual studio code

### ISSUE THREAD

**Issue by ssheduardo** [onecentlin/laravel5-snippets-vscode#6]
When install your plugin, the autocomplete of emmet is disabled.
If write html:5 or h2 and press TAB no autocomplete

Where are the error?

**Comment by onecentlin** [comment]
With Visual Studio Code v1.15+

Please update your User Profile:

```
    "emmet.includeLanguages": {
        "blade": "html"
    },
    "emmet.triggerExpansionOnTab": true,
```

Notice that `emmet.syntaxProfiles` is replaced with new property `emmet.includeLanguages`

**Comment by ssheduardo** [comment]
Thanks you, now is fine.
