### ISSUE TITLE
Feature Request: blade.php file formatting

### ISSUE THREAD

**Issue by shaneparsons** [onecentlin/laravel5-snippets-vscode#7]
I'm not sure if this should be requested here or on the vscode repo, but it'd be great if blade files could be formatted ("beautified") the same way all other files are (i.e. option+shift+f). So far all the methods I've tried have left undesirable results.

**Comment by onecentlin** [comment]
@shaneparsons The feature is added in [Laravel Blade Snippets](https://marketplace.visualstudio.com/items?itemName=onecentlin.laravel-blade) extension. Please try it out! =)
