### ISSUE TITLE
Add Form snippets of Laravel Collective

### ISSUE THREAD

**Issue by Ashu131** [onecentlin/laravel5-snippets-vscode#9]
##Need Support of Laravel Collective Snippets.
Like as shown in this image.

![form-snippet](https://user-images.githubusercontent.com/25302874/41806400-fe628614-76da-11e8-91b6-2c1459f85ab9.png)

**Comment by alshamsan** [comment]
Hi,
How can I disable only Form snippets in Blade?

Thanks
